steps:
- name: 'gcr.io/cloud-builders/npm'  
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'  
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/npm'  
  args: ['run', 'export']
- name: gcr.io/cloud-builders/gsutil
  args: [
    'find', 
    './out', 
    '-type', 
    'f', 
    '-name', 
    "'*.html'", 
    '-print0', 
    '|', 
    'while',
    'read', 
    '-d', 
    "$'\\0'", 
    'f',
    ';',
    'do', 
    'mv', 
    '"$f"', 
    '"${f%.html}"',
    ';', 
    'done']
- name: gcr.io/cloud-builders/gsutil
  args: ['rsync', '-d', '-r', 'out', 'gs://www.eredimonticelli.it']
timeout: "300s"
