# docker pull devillex/docker-firebase

steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'create-env']
  env:
    - EMAIL=${_EMAIL}
    - COMMIT_SHA=$COMMIT_SHA

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  env:
    - EMAIL=${_EMAIL}
    - COMMIT_SHA=$COMMIT_SHA

- name: devillex/docker-firebase
  args: [ 'firebase', 'deploy', '--project', '$PROJECT_ID', "--token", "$_TOKEN"]

timeout: "300s"