# docker pull devillex/docker-firebase

steps:
- name: 'node@22.20.0'
  entrypoint: 'npm'
  args: ['ci']

- name: 'node@22.20.0'
  entrypoint: 'npm'
  args: ['run', 'create-env']
  env:
    - EMAIL=${_EMAIL}
    - COMMIT_SHA=$COMMIT_SHA

- name: 'node@22.20.0'
  entrypoint: 'npm'
  args: ['run', 'build']
  env:
    - EMAIL=${_EMAIL}
    - COMMIT_SHA=$COMMIT_SHA

- name: devillex/docker-firebase
  args: [ 'firebase', 'deploy', '--project', '$PROJECT_ID', "--token", "$_TOKEN"]

timeout: "300s"
