steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  env:
    - EMAIL=${_EMAIL}
    - COMMIT_SHA=$COMMIT_SHA
- name: gcr.io/cloud-builders/gsutil
  args: ['rsync', '-d', '-r', 'public', 'gs://www.eredimonticelli.it']
timeout: "300s"
